/// Golden vectors for **V3-F5**, the production rating engine.
///
/// Every expected number in this file was GENERATED by running the audited
/// Ranking Lab implementation (`HybridEngine` bound to `kV3F5` in
/// `tools/ranking_simulation/engines.dart`) and pasted in. None of them was
/// derived by hand from a description, which is the whole point: the lab
/// engine is the mathematical source of truth, and this file is the contract
/// that `RatingEngineV3F5` and the SQL `_settle_rating_v3f5` both have to meet.
///
/// If you change a constant or a formula here, change it in
/// `lib/backend/models/rating_engine_v3f5.dart` AND in
/// `supabase/migration_player_app.sql` — and re-derive these numbers from the
/// lab rather than editing them to match whatever the code now produces.
///
/// `test/rating_engine_test.dart` holds the LEGACY v2 vectors and is
/// deliberately still passing. Between the two files it is possible to tell an
/// intentional migration difference from a port bug.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:padel_clay/backend/models/rating_engine_v3f5.dart';

const eps = 1e-9;

RatedPlayer p(String id, double r, double s, int n, {bool anchor = false}) =>
    RatedPlayer(
        id: id, rating: r, sigma: s, competitiveMatches: n, isAnchor: anchor);

/// Settles one doubles match and returns the moves keyed by player id.
Map<String, RatingMove> settle({
  required List<RatedPlayer> a,
  required List<RatedPlayer> b,
  required int gamesA,
  required int gamesB,
  required bool aWon,
}) {
  final moves = RatingEngineV3F5.settleMatch(
    team1: a,
    team2: b,
    team1Games: gamesA,
    team2Games: gamesB,
    outcome: aWon ? MatchOutcome.team1Win : MatchOutcome.team2Win,
  );
  return {for (final m in moves) m.id: m};
}

/// Four players, all at the given state, A wins [gamesA]-[gamesB].
Map<String, RatingMove> evenMatch(double r, double s, int n,
        {int gamesA = 12, int gamesB = 7}) =>
    settle(
      a: [p('a1', r, s, n), p('a2', r, s, n)],
      b: [p('b1', r, s, n), p('b2', r, s, n)],
      gamesA: gamesA,
      gamesB: gamesB,
      aWon: true,
    );

void main() {
  // ═══════════════════════════════════════════════════════════════════════
  // Engine identity + starting state (§2, §5)
  // ═══════════════════════════════════════════════════════════════════════
  group('engine identity and prior', () {
    test('production identifies as v3_f5, not v3_f', () {
      expect(kRatingEngineVersion, 'v3_f5');
    });

    test('starting prior is 3.30 and starting sigma 0.95', () {
      expect(RatingEngineV3F5.prior, 3.30);
      expect(RatingEngineV3F5.sigma0, 0.95);
    });

    test('rating range is 0.00–7.00', () {
      expect(RatingEngineV3F5.ratingMin, 0.0);
      expect(RatingEngineV3F5.ratingMax, 7.0);
    });

    test('public placement is exactly 5 competitive matches', () {
      expect(RatingEngineV3F5.placementMatches, 5);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // The K ladder — generated from the lab, one entry per match number (§10-13)
  // ═══════════════════════════════════════════════════════════════════════
  group('K by match number, fresh career', () {
    // K for a player's Nth match, starting from sigma 0.95 and playing on.
    // Matches 1-2 exploration, 3-4 calibration, 5 validation, 6+ the plain
    // sigma formula. NOTE the cliff between m5 (0.6197) and m6 (0.2929).
    const expectedK = <double>[
      1.1500000000, // m1  ┐ exploration, stage K 1.15
      1.1155000000, // m2  ┘
      0.8468100000, // m3  ┐ calibration, stage K 0.90
      0.8214057000, // m4  ┘
      0.6197049670, // m5    validation, stage K 0.70
      0.2928971706, // m6  ← post-placement 0.04 + 0.31·sigma, NOT an elevated stage
      0.2878392272, // m7
      0.2828824426, // m8
      0.2780247938, // m9
      0.2732642979, // m10
      0.2685990119, // m11
      0.2628840366, // m12
      0.2573119357, // m13
      0.2518791373, // m14
      0.2465821589, // m15
      0.2414176049, // m16
      0.2363821648, // m17
      0.2314726107, // m18
      0.2266857954, // m19
      0.2220186505, // m20
      0.2174681843, // m21
    ];

    test('every match reproduces the lab K exactly', () {
      var sigma = RatingEngineV3F5.sigma0;
      for (var i = 0; i < expectedK.length; i++) {
        final n = i; // matches already played before match i+1
        expect(RatingEngineV3F5.kFactor(sigma, n), closeTo(expectedK[i], eps),
            reason: 'K for match ${i + 1}');
        sigma = RatingEngineV3F5.decaySigma(sigma, n);
      }
    });

    test('matches 6-10 do NOT get a special elevated K stage', () {
      // K falls monotonically from match 6 onward, purely because sigma falls.
      for (var i = 5; i < expectedK.length - 1; i++) {
        expect(expectedK[i + 1], lessThan(expectedK[i]));
      }
      // and each one is exactly 0.04 + 0.31·sigma
      var sigma = RatingEngineV3F5.sigma0;
      for (var n = 0; n < 5; n++) {
        sigma = RatingEngineV3F5.decaySigma(sigma, n);
      }
      expect(RatingEngineV3F5.kFactor(sigma, 5), closeTo(0.04 + 0.31 * sigma, eps));
    });

    test('the match 5 → 6 K cliff is preserved, not smoothed', () {
      // Known V3-F5 characteristic: K drops by more than half in one match.
      expect(expectedK[4] / expectedK[5], greaterThan(2.0));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Sigma — deterministic bands, no adaptivity (§19, §20)
  // ═══════════════════════════════════════════════════════════════════════
  group('sigma decay bands', () {
    const expectedSigma = <double>[
      0.9215000000, // after m1  ┐
      0.8938550000, // after m2  │ band 0.970, matches 1-5
      0.8670393500, // after m3  │
      0.8410281695, // after m4  │
      0.8157973244, // after m5  ┘ ← reveal happens here, sigma still 0.82
      0.7994813779, // after m6  ┐
      0.7834917504, // after m7  │ band 0.980, matches 6-10
      0.7678219154, // after m8  │
      0.7524654771, // after m9  │
      0.7374161675, // after m10 ┘
      0.7189807633, // after m11 ┐
      0.7010062442, // after m12 │
      0.6834810881, // after m13 │
      0.6663940609, // after m14 │
      0.6497342094, // after m15 │ band 0.975, matches 11-20
      0.6334908542, // after m16 │
      0.6176535828, // after m17 │
      0.6022122432, // after m18 │
      0.5871569372, // after m19 │
      0.5724780137, // after m20 ┘
      0.5553036733, // after m21 ← band 0.970, established
    ];

    test('reproduces the lab sigma ladder exactly', () {
      var sigma = RatingEngineV3F5.sigma0;
      for (var i = 0; i < expectedSigma.length; i++) {
        sigma = RatingEngineV3F5.decaySigma(sigma, i);
        expect(sigma, closeTo(expectedSigma[i], eps),
            reason: 'sigma after match ${i + 1}');
      }
    });

    test('sigmaAfter() agrees with iterated decay', () {
      for (final n in [0, 1, 5, 6, 10, 11, 20, 21, 50]) {
        var s = RatingEngineV3F5.sigma0;
        for (var i = 0; i < n; i++) {
          s = RatingEngineV3F5.decaySigma(s, i);
        }
        expect(RatingEngineV3F5.sigmaAfter(n), closeTo(s, eps));
      }
    });

    group('band boundaries land on the right match — no off-by-one', () {
      test('matches 1-5 use 0.970 (n = 0..4, read before increment)', () {
        for (final n in [0, 1, 2, 3, 4]) {
          expect(RatingEngineV3F5.sigmaDecayFor(n), 0.970, reason: 'n=$n');
        }
      });
      test('matches 6-10 use 0.980 (n = 5..9)', () {
        for (final n in [5, 6, 7, 8, 9]) {
          expect(RatingEngineV3F5.sigmaDecayFor(n), 0.980, reason: 'n=$n');
        }
      });
      test('matches 11-20 use 0.975 (n = 10..19)', () {
        for (final n in [10, 11, 18, 19]) {
          expect(RatingEngineV3F5.sigmaDecayFor(n), 0.975, reason: 'n=$n');
        }
      });
      test('match 21+ uses the established 0.970 (n >= 20)', () {
        for (final n in [20, 21, 50, 500]) {
          expect(RatingEngineV3F5.sigmaDecayFor(n), 0.970, reason: 'n=$n');
        }
      });
      test('the bands approach 0.970 from ABOVE and never dip below it', () {
        for (var n = 0; n < 40; n++) {
          expect(RatingEngineV3F5.sigmaDecayFor(n),
              greaterThanOrEqualTo(RatingEngineV3F5.sigmaDecay));
        }
      });
    });

    test('sigma floors at 0.12 for a deep veteran', () {
      expect(RatingEngineV3F5.sigmaAfter(400), closeTo(0.12, eps));
    });

    test('ADAPTIVE SIGMA IS OFF: decay ignores the result entirely', () {
      // Known, documented weakness — a player can be confidently wrong. This
      // test exists so switching adaptive sigma on is a deliberate act that
      // breaks a named assertion, not a quiet drift.
      final crushed = evenMatch(3.5, 0.50, 30, gamesA: 0, gamesB: 12);
      final thrashed = evenMatch(3.5, 0.50, 30, gamesA: 12, gamesB: 0);
      expect(crushed['a1']!.sigmaAfter, closeTo(thrashed['a1']!.sigmaAfter, eps));

      // and a massive upset shrinks sigma exactly as much as a formality
      final upset = settle(
        a: [p('a1', 1.0, 0.50, 30), p('a2', 1.0, 0.50, 30)],
        b: [p('b1', 6.0, 0.50, 30), p('b2', 6.0, 0.50, 30)],
        gamesA: 12, gamesB: 4, aWon: true,
      );
      expect(upset['a1']!.sigmaAfter, closeTo(thrashed['a1']!.sigmaAfter, eps));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Model shape (§6, §7, §8, §15, §18)
  // ═══════════════════════════════════════════════════════════════════════
  group('expected score E', () {
    test('equal team strengths → 0.5', () {
      expect(RatingEngineV3F5.expected(3.3, 3.3), closeTo(0.5, eps));
    });
    test('one level behind → 1/11 (logistic scale 1.0)', () {
      expect(RatingEngineV3F5.expected(3.0, 4.0), closeTo(1 / 11, eps));
    });
    test('E(a,b) + E(b,a) == 1', () {
      expect(RatingEngineV3F5.expected(2.3, 5.1) + RatingEngineV3F5.expected(5.1, 2.3),
          closeTo(1.0, 1e-12));
    });
    test('settlement takes E_opponent as the exact complement', () {
      final m = settle(
        a: [p('a1', 5.0, 0.5, 30)],
        b: [p('b1', 2.0, 0.5, 30)],
        gamesA: 12, gamesB: 5, aWon: true,
      );
      expect(m['a1']!.expected + m['b1']!.expected, 1.0);
    });
  });

  group('team strength — pure average, lambda stays 0', () {
    test('5.0 + 2.0 and 3.5 + 3.5 are the SAME team strength', () {
      // Known limitation, deliberately not fixed in this migration.
      expect(RatingEngineV3F5.teamStrength([5.0, 2.0]),
          closeTo(RatingEngineV3F5.teamStrength([3.5, 3.5]), eps));
    });

    test('G9: the uneven pair and the even pair get identical deltas', () {
      final m = settle(
        a: [p('strong', 5.0, 0.30, 30), p('weak', 2.0, 0.30, 30)],
        b: [p('b1', 3.5, 0.30, 30), p('b2', 3.5, 0.30, 30)],
        gamesA: 12, gamesB: 8, aWon: true,
      );
      expect(m['strong']!.expected, closeTo(0.5, eps));
      expect(m['strong']!.delta, closeTo(0.0536987500, eps));
      expect(m['weak']!.delta, closeTo(0.0536987500, eps));
      expect(m['strong']!.ratingAfter, closeTo(5.0536987500, eps));
      expect(m['weak']!.ratingAfter, closeTo(2.0536987500, eps));
      expect(m['b1']!.delta, closeTo(-0.0536987500, eps));
    });
  });

  group('score signal S — 0.85 result + 0.15 saturating margin', () {
    test('a 12-7 win gives S = 0.9907894737', () {
      expect(RatingEngineV3F5.scoreSignal(1.0, 12, 7), closeTo(0.9907894737, eps));
    });
    test('S(win) + S(loss) == 1 for any scoreline', () {
      for (final g in [[12, 7], [12, 0], [14, 12], [10, 10], [0, 0]]) {
        expect(
            RatingEngineV3F5.scoreSignal(1.0, g[0], g[1]) +
                RatingEngineV3F5.scoreSignal(0.0, g[1], g[0]),
            closeTo(1.0, 1e-12),
            reason: '$g');
      }
    });
    test('no games recorded → margin defaults to an even split', () {
      expect(RatingEngineV3F5.marginRatio(0, 0), closeTo(0.5, eps));
      expect(RatingEngineV3F5.scoreSignal(1.0, 0, 0), closeTo(0.925, eps));
    });
    test('the margin saturates: 6-0 6-0 == 6-2 6-2', () {
      expect(RatingEngineV3F5.scoreSignal(1.0, 12, 0),
          closeTo(RatingEngineV3F5.scoreSignal(1.0, 12, 4), eps));
      expect(RatingEngineV3F5.scoreSignal(1.0, 12, 0), closeTo(1.0, eps));
    });
    test('the v2 signal (0.7 result + 0.3 raw ratio) is GONE', () {
      // v2 would have given 0.7 + 0.3·(12/19) = 0.8894737 here.
      expect(RatingEngineV3F5.scoreSignal(1.0, 12, 7),
          isNot(closeTo(0.7 + 0.3 * (12 / 19), 1e-6)));
    });
    test('margin is worth at most 0.15 of signal, result 0.85', () {
      final best = RatingEngineV3F5.scoreSignal(1.0, 12, 0);
      final worst = RatingEngineV3F5.scoreSignal(1.0, 10, 9);
      expect(best - worst, lessThanOrEqualTo(0.15 + eps));
    });
  });

  group('opponent reliability W', () {
    test('W is pinned to exactly 1.00 for every match in placement', () {
      for (var n = 0; n < 5; n++) {
        for (final oppSigma in [0.12, 0.50, 0.95, 1.0]) {
          expect(RatingEngineV3F5.wOpp(oppSigma, n), 1.0,
              reason: 'n=$n oppSigma=$oppSigma');
        }
      }
    });
    test('once established the floor is 0.65, not v2\'s 0.50', () {
      expect(RatingEngineV3F5.wOpp(1.0, 5), 0.65);
      expect(RatingEngineV3F5.wOpp(0.95, 30), closeTo(0.65, eps));
    });
    test('reliable opponents raise W above the floor', () {
      expect(RatingEngineV3F5.wOpp(0.12, 30), closeTo(0.94, eps));
      expect(RatingEngineV3F5.wOpp(0.50, 30), closeTo(0.75, eps));
      expect(RatingEngineV3F5.wOpp(0.30, 30), closeTo(0.85, eps));
    });
    test('W never exceeds 1.0 or falls below 0.65 outside placement', () {
      for (final s in [0.0, 0.12, 0.4, 0.7, 1.0]) {
        final w = RatingEngineV3F5.wOpp(s, 30);
        expect(w, inInclusiveRange(0.65, 1.0));
      }
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Placement, match by match (§9-13, §40)
  // ═══════════════════════════════════════════════════════════════════════
  group('placement career — four brand-new equal players', () {
    test('G1 match 1 WIN: every input and the result', () {
      final m = evenMatch(3.30, 0.95, 0);
      final w = m['a1']!;
      expect(w.teamStrength, closeTo(3.30, eps));
      expect(w.oppStrength, closeTo(3.30, eps));
      expect(w.expected, closeTo(0.5, eps));
      expect(w.signal, closeTo(0.9907894737, eps));
      expect(w.w, closeTo(1.0, eps));
      expect(w.k, closeTo(1.1500000000, eps));
      expect(w.delta, closeTo(0.5644078947, eps));
      expect(w.ratingAfter, closeTo(3.8644078947, eps));
      expect(w.sigmaAfter, closeTo(0.9215000000, eps));
      expect(w.inPlacement, isTrue);
      expect(w.matchNumber, 1);
    });

    test('G2 match 1 LOSS is the exact mirror', () {
      final l = evenMatch(3.30, 0.95, 0)['b1']!;
      expect(l.signal, closeTo(0.0092105263, eps));
      expect(l.delta, closeTo(-0.5644078947, eps));
      expect(l.ratingAfter, closeTo(2.7355921053, eps));
      expect(l.sigmaAfter, closeTo(0.9215000000, eps));
    });

    test('teammates get the SAME delta when their state matches', () {
      final m = evenMatch(3.30, 0.95, 0);
      expect(m['a1']!.delta, closeTo(m['a2']!.delta, 1e-12));
    });

    // Each entry: (matches already played, expected K, delta, rating after).
    // A player n matches in, on sigma from the ladder, vs three fresh players.
    const stages = <(int, double, double, double)>[
      (1, 1.1155000000, 0.5474756579, 3.8474756579), // m2  exploration
      (2, 0.8468100000, 0.4156054342, 3.7156054342), // m3  calibration
      (3, 0.8214057000, 0.4031372712, 3.7031372712), // m4  calibration
      (4, 0.6197049670, 0.3041446746, 3.6041446746), // m5  validation + reveal
      (5, 0.2928971706, 0.0934380513, 3.3934380513), // m6  post-placement
      (9, 0.2732642979, 0.0871749066, 3.3871749066), // m10 end of 0.980 band
      (10, 0.2685990119, 0.0856866190, 3.3856866190), // m11 start of 0.975
      (19, 0.2220186505, 0.0708268708, 3.3708268708), // m20 end of 0.975
      (20, 0.2174681843, 0.0693752122, 3.3693752122), // m21 established
    ];

    for (final (n, k, delta, after) in stages) {
      test('match ${n + 1}: K=$k, delta=$delta', () {
        final sigma = RatingEngineV3F5.sigmaAfter(n);
        final m = settle(
          a: [p('me', 3.30, sigma, n), p('a2', 3.30, 0.95, 0)],
          b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
          gamesA: 12, gamesB: 7, aWon: true,
        );
        final me = m['me']!;
        expect(me.k, closeTo(k, eps));
        expect(me.delta, closeTo(delta, eps));
        expect(me.ratingAfter, closeTo(after, eps));
        expect(me.matchNumber, n + 1);
      });
    }

    test('W collapses from 1.00 to 0.65 at the placement boundary', () {
      // Same opponents, same everything — only the player's match count moves.
      final inP = settle(
        a: [p('me', 3.30, 0.8410281695, 4), p('x', 3.30, 0.95, 0)],
        b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['me']!;
      final outP = settle(
        a: [p('me', 3.30, 0.8157973244, 5), p('x', 3.30, 0.95, 0)],
        b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['me']!;
      expect(inP.w, 1.0);
      expect(outP.w, 0.65);
      expect(inP.inPlacement, isTrue);
      expect(outP.inPlacement, isFalse);
    });

    test('the 5th match is the one that reveals the rating', () {
      expect(RatingEngineV3F5.isRevealed(4), isFalse);
      expect(RatingEngineV3F5.isRevealed(5), isTrue);
      final fifth = settle(
        a: [p('me', 3.30, RatingEngineV3F5.sigmaAfter(4), 4), p('x', 3.30, 0.95, 0)],
        b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['me']!;
      expect(fifth.revealsRating, isTrue);
      expect(fifth.matchNumber, RatingEngineV3F5.placementMatches);
      // ...and it reveals a rating the engine is still far from sure about.
      expect(fifth.sigmaAfter, closeTo(0.8157973244, eps));
    });

    test('match 5 performs NO statistical validation — it is a stage name', () {
      // Nothing about the 5th settlement differs in kind from the 4th: same
      // formula, different stage K. If a real test were ever added it would
      // have to change this assertion deliberately.
      final fourth = settle(
        a: [p('me', 3.30, RatingEngineV3F5.sigmaAfter(3), 3), p('x', 3.30, 0.95, 0)],
        b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['me']!;
      final fifth = settle(
        a: [p('me', 3.30, RatingEngineV3F5.sigmaAfter(4), 4), p('x', 3.30, 0.95, 0)],
        b: [p('b1', 3.30, 0.95, 0), p('b2', 3.30, 0.95, 0)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['me']!;
      expect(fifth.signal, closeTo(fourth.signal, eps));
      expect(fifth.expected, closeTo(fourth.expected, eps));
      expect(fifth.w, closeTo(fourth.w, eps));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // §16 — the known winner-negative-delta behaviour. PRESERVED ON PURPOSE.
  // ═══════════════════════════════════════════════════════════════════════
  group('KNOWN V3-F5 BEHAVIOUR: a huge favourite can lose rating by winning', () {
    test('G4 6.5 pair beats a 1.0 pair 6-4 6-4 → delta is NEGATIVE', () {
      final m = settle(
        a: [p('fav1', 6.5, 0.30, 40), p('fav2', 6.5, 0.30, 40)],
        b: [p('dog1', 1.0, 0.30, 40), p('dog2', 1.0, 0.30, 40)],
        gamesA: 12, gamesB: 8, aWon: true,
      );
      final fav = m['fav1']!;
      expect(fav.expected, closeTo(0.9999968377, eps));
      expect(fav.signal, closeTo(0.9750000000, eps));
      expect(fav.signal, lessThan(fav.expected)); // S < E is the cause
      expect(fav.delta, closeTo(-0.0028258925, eps));
      expect(fav.delta, lessThan(0));
      expect(fav.ratingAfter, closeTo(6.4971741075, eps));

      // This is NOT to be clamped away. If someone adds
      // `if (won) delta = max(delta, 0)` this test is what fails.
    });

    test('G5 the same favourite winning 6-1 6-1 is (barely) positive', () {
      final m = settle(
        a: [p('fav1', 6.5, 0.30, 40), p('fav2', 6.5, 0.30, 40)],
        b: [p('dog1', 1.0, 0.30, 40), p('dog2', 1.0, 0.30, 40)],
        gamesA: 12, gamesB: 2, aWon: true,
      );
      expect(m['fav1']!.signal, closeTo(1.0, eps));
      expect(m['fav1']!.delta, closeTo(0.0000003575, eps));
      expect(m['fav1']!.delta, greaterThan(0));
    });

    test('at E ≈ 0.99 the crossover is a games ratio of ~0.630', () {
      // A 2.0-level gap gives E = 0.990099, so the winner needs
      // S = 0.85 + 0.15·rho' > 0.990099, i.e. rho > 0.6302.
      double deltaFor(int gf, int ga) => settle(
            a: [p('fav1', 5.0, 0.30, 40), p('fav2', 5.0, 0.30, 40)],
            b: [p('dog1', 3.0, 0.30, 40), p('dog2', 3.0, 0.30, 40)],
            gamesA: gf, gamesB: ga, aWon: true,
          )['fav1']!.delta;
      expect(settle(
        a: [p('fav1', 5.0, 0.30, 40), p('fav2', 5.0, 0.30, 40)],
        b: [p('dog1', 3.0, 0.30, 40), p('dog2', 3.0, 0.30, 40)],
        gamesA: 12, gamesB: 7, aWon: true,
      )['fav1']!.expected, closeTo(0.990099, 1e-6));
      expect(deltaFor(12, 8), lessThan(0)); // ratio 0.600 — below the crossover
      expect(deltaFor(12, 7), greaterThan(0)); // ratio 0.632 — above it
    });

    test('at E ≈ 0.999997 only a saturated margin is enough to gain', () {
      // With a 5.5-level gap the required S exceeds anything short of the
      // margin cap, so even a 12-7 win still costs the favourite rating. The
      // crossover moves with E — it is not a fixed scoreline.
      double deltaFor(int gf, int ga) => settle(
            a: [p('fav1', 6.5, 0.30, 40), p('fav2', 6.5, 0.30, 40)],
            b: [p('dog1', 1.0, 0.30, 40), p('dog2', 1.0, 0.30, 40)],
            gamesA: gf, gamesB: ga, aWon: true,
          )['fav1']!.delta;
      expect(deltaFor(12, 8), lessThan(0)); // ratio 0.600
      expect(deltaFor(12, 7), lessThan(0)); // ratio 0.632 — STILL negative
      expect(deltaFor(12, 6), greaterThan(0)); // ratio 0.667 — margin saturated
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // §17 — score shapes, including the tie-break path the lab never exercised
  // ═══════════════════════════════════════════════════════════════════════
  group('score parsing and tie-breaks', () {
    test('a championship tie-break counts as ONE game to its winner', () {
      final g = parseSetGames('6-4,3-6,10-7');
      expect(g.team1, 6 + 3 + 1);
      expect(g.team2, 4 + 6 + 0);
    });
    test('a normal 7-6 set counts as seven games, not a tie-break', () {
      final g = parseSetGames('7-6,7-6');
      expect(g.team1, 14);
      expect(g.team2, 12);
    });
    test('straight-set shapes', () {
      expect(parseSetGames('6-0,6-0'), (team1: 12, team2: 0));
      expect(parseSetGames('6-2,6-2'), (team1: 12, team2: 4));
      expect(parseSetGames('6-4,6-4'), (team1: 12, team2: 8));
    });
    test('split sets with a normal third', () {
      expect(parseSetGames('6-4,3-6,6-2'), (team1: 15, team2: 12));
    });
    test('empty / null → 0-0, which the engine reads as an even split', () {
      expect(parseSetGames(null), (team1: 0, team2: 0));
      expect(parseSetGames(''), (team1: 0, team2: 0));
    });

    // Established even teams, A wins. Deltas generated from the lab.
    const shapes = <(String, double, double)>[
      ('6-0,6-0', 1.0000000000, 0.0731250000),
      ('6-2,6-2', 1.0000000000, 0.0731250000), // identical — margin saturates
      ('6-4,6-4', 0.9750000000, 0.0694687500),
      ('7-6,7-6', 0.9442307692, 0.0649687500),
      ('6-4,3-6,10-7', 0.9250000000, 0.0621562500), // tie-break path
    ];

    for (final (score, signal, delta) in shapes) {
      test('$score → S=$signal, delta=$delta', () {
        final g = parseSetGames(score);
        final m = settle(
          a: [p('a1', 3.5, 0.50, 30), p('a2', 3.5, 0.50, 30)],
          b: [p('b1', 3.5, 0.50, 30), p('b2', 3.5, 0.50, 30)],
          gamesA: g.team1, gamesB: g.team2, aWon: true,
        );
        expect(m['a1']!.signal, closeTo(signal, eps));
        expect(m['a1']!.delta, closeTo(delta, eps));
      });
    }

    test('a 10-7 tie-break does NOT count as ten games', () {
      // If it did, the games ratio would be 10/17 rather than 1/1 for the set
      // and the delta would differ. This is the branch the lab's generated
      // worlds never reached, so it is pinned explicitly here.
      final asTieBreak = parseSetGames('6-4,3-6,10-7');
      expect(asTieBreak.team1, 10);
      expect(asTieBreak.team2, 10);
      expect(asTieBreak.team1, isNot(6 + 3 + 10));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Established play, upsets, clamps, anchors (§40)
  // ═══════════════════════════════════════════════════════════════════════
  group('established play', () {
    test('G6 even established teams, close win', () {
      final m = evenMatch(3.5, 0.50, 30, gamesA: 12, gamesB: 8);
      expect(m['a1']!.k, closeTo(0.1950000000, eps));
      expect(m['a1']!.w, closeTo(0.75, eps));
      expect(m['a1']!.delta, closeTo(0.0694687500, eps));
      expect(m['a1']!.sigmaAfter, closeTo(0.4850000000, eps));
    });

    test('G7 upset — a 2.0 pair beats a 5.0 pair 12-9', () {
      final m = settle(
        a: [p('u1', 2.0, 0.40, 30), p('u2', 2.0, 0.40, 30)],
        b: [p('f1', 5.0, 0.40, 30), p('f2', 5.0, 0.40, 30)],
        gamesA: 12, gamesB: 9, aWon: true,
      );
      expect(m['u1']!.expected, closeTo(0.0009990010, eps));
      expect(m['u1']!.delta, closeTo(0.1259146454, eps));
      expect(m['u1']!.ratingAfter, closeTo(2.1259146454, eps));
      expect(m['f1']!.delta, closeTo(-0.1259146454, eps));
      // symmetric here ONLY because both sides share sigma and match count
      expect(m['u1']!.delta, closeTo(-m['f1']!.delta, 1e-12));
    });

    test('the engine is NOT zero-sum when the two sides differ', () {
      final m = settle(
        a: [p('new1', 3.3, 0.95, 0), p('new2', 3.3, 0.95, 0)],
        b: [p('vet1', 3.3, 0.20, 60), p('vet2', 3.3, 0.20, 60)],
        gamesA: 12, gamesB: 7, aWon: true,
      );
      final total = m.values.map((v) => v.delta).reduce((x, y) => x + y);
      expect(total.abs(), greaterThan(0.1)); // known, documented
    });

    test('G8 new vs established: the new player moves a long way', () {
      final m = settle(
        a: [p('me', 3.30, 0.95, 0), p('x', 3.30, 0.95, 0)],
        b: [p('v1', 4.0, 0.25, 50), p('v2', 4.0, 0.25, 50)],
        gamesA: 12, gamesB: 6, aWon: true,
      );
      final me = m['me']!;
      expect(me.expected, closeTo(0.1663375308, eps));
      expect(me.w, 1.0); // in placement — the established pair is NOT discounted
      expect(me.k, closeTo(1.15, eps));
      expect(me.delta, closeTo(0.9587118396, eps));
      expect(me.ratingAfter, closeTo(4.2587118396, eps));
    });
  });

  group('clamps and anchors', () {
    test('G11 rating clamps at 7.0', () {
      final m = settle(
        a: [p('top', 7.0, 0.95, 0), p('x', 7.0, 0.95, 0)],
        b: [p('b1', 1.0, 0.95, 0), p('b2', 1.0, 0.95, 0)],
        gamesA: 12, gamesB: 0, aWon: true,
      );
      expect(m['top']!.ratingAfter, 7.0);
      expect(m['top']!.ratingAfter, lessThanOrEqualTo(RatingEngineV3F5.ratingMax));
    });

    test('G12 rating clamps at 0.0', () {
      final m = settle(
        a: [p('bot', 0.0, 0.95, 0), p('x', 0.0, 0.95, 0)],
        b: [p('b1', 6.0, 0.95, 0), p('b2', 6.0, 0.95, 0)],
        gamesA: 0, gamesB: 12, aWon: false,
      );
      expect(m['bot']!.ratingAfter, 0.0);
    });

    test('G10 an anchor is a SOFT pin: it still moves, capped at ±0.05', () {
      final m = settle(
        a: [p('anchor', 3.0, 0.30, 30, anchor: true), p('x', 3.0, 0.30, 30)],
        b: [p('b1', 6.5, 0.30, 30), p('b2', 6.5, 0.30, 30)],
        gamesA: 1, gamesB: 12, aWon: false,
      );
      final a = m['anchor']!;
      expect(a.delta.abs(), lessThanOrEqualTo(0.05 + 1e-12));
      expect(a.delta, closeTo(-0.0000357382, eps));
      // sigma decays for an anchor exactly like anyone else
      expect(a.sigmaAfter, closeTo(0.2910000000, eps));
    });

    test('an anchor facing a large delta is clamped to exactly ±0.05', () {
      final m = settle(
        a: [p('anchor', 3.0, 0.95, 0, anchor: true), p('x', 3.0, 0.95, 0)],
        b: [p('b1', 6.5, 0.95, 0), p('b2', 6.5, 0.95, 0)],
        gamesA: 12, gamesB: 2, aWon: true,
      );
      expect(m['anchor']!.delta, closeTo(0.05, 1e-12));
      expect(m['anchor']!.anchorClamped, isTrue);
    });

    test('G13 a 0-0 scoreline settles on the result alone', () {
      final m = evenMatch(3.30, 0.95, 0, gamesA: 0, gamesB: 0);
      expect(m['a1']!.signal, closeTo(0.925, eps));
      expect(m['a1']!.delta, closeTo(0.4887500000, eps));
      expect(m['a1']!.ratingAfter, closeTo(3.7887500000, eps));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Precision policy (§22, §23)
  // ═══════════════════════════════════════════════════════════════════════
  group('precision: internal math vs public display', () {
    test('the engine itself does no rounding', () {
      final m = evenMatch(3.30, 0.95, 0);
      // 3.8644078947... is not representable at 2dp — the raw value survives.
      expect(m['a1']!.ratingAfter, closeTo(3.8644078947, eps));
      expect(m['a1']!.ratingAfter, isNot(closeTo(3.86, 1e-4)));
    });

    test('storage quantises at 6dp, far below the 0.25 display step', () {
      expect(RatingEngineV3F5.storedRating(3.8644078947), closeTo(3.864408, 1e-12));
      expect(RatingEngineV3F5.storedRating(3.8644078947),
          closeTo(3.8644078947, 1e-6));
    });

    test('storage rounding cannot accumulate into a visible drift', () {
      // 200 matches of worst-case 5e-7 quantisation is still 1e-4.
      var exact = 3.30, stored = 3.30;
      for (var n = 0; n < 200; n++) {
        final sigma = RatingEngineV3F5.sigmaAfter(n);
        final e = settle(
          a: [p('e', exact, sigma, n), p('x', 3.3, 0.5, 30)],
          b: [p('b1', 3.4, 0.5, 30), p('b2', 3.4, 0.5, 30)],
          gamesA: 12, gamesB: 9, aWon: n.isEven,
        )['e']!;
        final s = settle(
          a: [p('s', stored, sigma, n), p('x', 3.3, 0.5, 30)],
          b: [p('b1', 3.4, 0.5, 30), p('b2', 3.4, 0.5, 30)],
          gamesA: 12, gamesB: 9, aWon: n.isEven,
        )['s']!;
        exact = e.ratingAfter;
        stored = RatingEngineV3F5.storedRating(s.ratingAfter);
      }
      expect((exact - stored).abs(), lessThan(1e-4));
    });

    test('2dp storage — what v2 did — WOULD have visibly drifted', () {
      // Justifies widening the column rather than keeping numeric(3,2).
      double round2(double v) => (v * 100).round() / 100;
      var exact = 3.30, coarse = 3.30;
      for (var n = 0; n < 200; n++) {
        final sigma = RatingEngineV3F5.sigmaAfter(n);
        exact = settle(
          a: [p('e', exact, sigma, n), p('x', 3.3, 0.5, 30)],
          b: [p('b1', 3.4, 0.5, 30), p('b2', 3.4, 0.5, 30)],
          gamesA: 12, gamesB: 9, aWon: n.isEven,
        )['e']!.ratingAfter;
        coarse = round2(settle(
          a: [p('c', coarse, sigma, n), p('x', 3.3, 0.5, 30)],
          b: [p('b1', 3.4, 0.5, 30), p('b2', 3.4, 0.5, 30)],
          gamesA: 12, gamesB: 9, aWon: n.isEven,
        )['c']!.ratingAfter);
      }
      expect((exact - coarse).abs(), greaterThan(1e-3));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // §14 / §24 — placement complete is NOT the same claim as confident
  // ═══════════════════════════════════════════════════════════════════════
  group('placement gate vs confidence gate', () {
    test('the rating is public at 5 matches while still flagged provisional', () {
      expect(RatingEngineV3F5.isRevealed(5), isTrue);
      expect(RatingEngineV3F5.isProvisional(RatingEngineV3F5.sigmaAfter(5), 5),
          isTrue);
    });

    test('the confidence gate clears at 20 matches, not 5', () {
      expect(RatingEngineV3F5.isProvisional(RatingEngineV3F5.sigmaAfter(19), 19),
          isTrue);
      expect(RatingEngineV3F5.isProvisional(RatingEngineV3F5.sigmaAfter(20), 20),
          isFalse);
    });

    test('the sigma threshold is derived: it brackets matches 19 and 20', () {
      expect(RatingEngineV3F5.sigmaAfter(19),
          greaterThan(RatingEngineV3F5.provisionalMaxSigma));
      expect(RatingEngineV3F5.sigmaAfter(20),
          lessThan(RatingEngineV3F5.provisionalMaxSigma));
    });

    test('a hand-set low sigma still needs the match count', () {
      // An admin marking an anchor sets sigma 0.30; the RPC also pushes
      // competitive_matches to 20 so the flag actually clears.
      expect(RatingEngineV3F5.isProvisional(0.30, 10), isTrue);
      expect(RatingEngineV3F5.isProvisional(0.30, 20), isFalse);
    });
  });
}
