-- ===========================================================================
-- V3-F5 post-deploy verification — READ ONLY. Changes nothing, writes nothing.
-- Run AFTER 2026-08-13_rating_engine_v3f5.sql. Safe to run any time, twice,
-- or on a busy database.
--
-- Two things are checked, and the second is the one that matters:
--
--   A. SCHEMA + WIRING — did the delta actually land.
--   B. THE MATHS, against the golden vectors in
--      test/rating_engine_v3f5_test.dart.
--
-- (B) is the piece the Dart test suite could NOT prove. Those tests pin the
-- Ranking Lab against the Dart port, both of which use IEEE doubles; Postgres
-- computes in `numeric`, a different number system. This script is the only
-- place the SQL engine's own arithmetic is compared with the numbers V3-F5 was
-- selected on. Every expected value below was generated by running the lab
-- engine, not derived by hand.
--
-- Every row should read PASS. Any FAIL means production is not computing what
-- was validated — stop and report it rather than settling matches on it.
-- ===========================================================================

with checks(sort, label, ok) as (

  -- ── A. schema + wiring ────────────────────────────────────────────────
  select 1, 'profiles.rating is numeric(9,6) — full internal precision',
    coalesce((select numeric_precision = 9 and numeric_scale = 6
                from information_schema.columns
               where table_schema = 'public' and table_name = 'profiles'
                 and column_name = 'rating'), false)

  union all select 2, 'profiles.sigma defaults to the V3-F5 prior 0.95',
    coalesce((select column_default like '%0.95%'
                from information_schema.columns
               where table_schema = 'public' and table_name = 'profiles'
                 and column_name = 'sigma'), false)

  union all select 3, 'is_provisional uses the recalibrated 0.58 / 20 gate',
    coalesce((select pg_get_expr(d.adbin, d.adrelid) like '%0.58%'
                from pg_attrdef d
                join pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum
               where d.adrelid = 'public.profiles'::regclass
                 and a.attname = 'is_provisional'), false)

  union all select 4, 'ranking_history records engine provenance',
    (select count(*) = 6 from information_schema.columns
      where table_schema = 'public' and table_name = 'ranking_history'
        and column_name in
            ('engine_version','match_no','k_factor','w_opp','expected','signal'))

  union all select 5, 'the engine, the rollback path and the helper all exist',
    (select count(distinct proname) = 4 from pg_proc
      where pronamespace = 'public'::regnamespace
        and proname in ('_settle_rating_v3f5','_settle_rating_v2',
                        '_v3f5_margin','rating_engine_version'))

  union all select 6, '_settle_rating dispatches and refuses casual matches',
    coalesce((select prosrc like '%_settle_rating_v3f5%'
                 and prosrc like '%_settle_rating_v2%'
                 and prosrc like '%ranked%'
                from pg_proc where proname = '_settle_rating'
                 and pronamespace = 'public'::regnamespace limit 1), false)

  union all select 7, 'the live engine selector says v3_f5',
    (public.rating_engine_version() = 'v3_f5')

  union all select 8, 'the hidden prior is 3.30, not v2''s 2.0',
    coalesce((select prosrc like '%3.30%' from pg_proc
               where proname = '_settle_rating_v3f5'
                 and pronamespace = 'public'::regnamespace limit 1), false)

  union all select 9, 'inactivity no longer cuts a rating',
    coalesce((select prosrc not like '%0.04%' and prosrc not like '%set rating%'
                from pg_proc where proname = 'apply_rating_decay'
                 and pronamespace = 'public'::regnamespace limit 1), false)

  -- ── B. the maths, vs the golden vectors ───────────────────────────────

  -- A championship tie-break is ONE game to its winner, not ten. This is the
  -- branch the lab's generated match worlds never reached.
  union all select 20, 'tie-break: ''6-4,3-6,10-7'' parses to 10 games all',
    coalesce((select a = 10 and b = 10
                from public._parse_set_games('6-4,3-6,10-7')), false)

  union all select 21, 'margin saturates: 6-0 6-0 scores the same as 6-2 6-2',
    (public._v3f5_margin(12, 0) = public._v3f5_margin(12, 4)
     and public._v3f5_margin(12, 0) = 1.0)

  union all select 22, 'margin is symmetric: rho''(a,b) + rho''(b,a) = 1',
    (abs(public._v3f5_margin(12, 7) + public._v3f5_margin(7, 12) - 1.0) < 1e-12)

  union all select 23, 'margin with no games recorded is an even split',
    (public._v3f5_margin(0, 0) = 0.5)

  -- G1 — four brand-new equal players (3.30 / sigma 0.95 / 0 matches), A wins
  -- 12-7. K 1.15, W 1.00, E 0.5, S 0.990789473684. Lab delta +0.564407894737.
  union all select 24, 'G1 placement match 1: delta = +0.5644078947',
    (abs(
       (1.15 * greatest(0.35, least(1.0, 0.95 / 0.95)))            -- K
       * greatest(0.5 + 0.5 * (1 - 0.95), 1.00)                    -- W, floored at 1.00 in placement
       * ((0.85 * 1 + 0.15 * public._v3f5_margin(12, 7))           -- S
          - (1.0 / (1.0 + power(10.0, (3.3 - 3.3) / 1.0))))        -- E
     - 0.564407894736842) < 1e-9)

  -- G4 — THE KNOWN ONE. A 6.5 pair (sigma 0.30, 40 matches) beats a 1.0 pair
  -- 6-4 6-4. S 0.975 < E 0.9999968, so the WINNER LOSES rating. If this reads
  -- FAIL because the delta came out positive, someone has "fixed" the engine.
  union all select 25, 'G4 huge favourite wins narrowly: delta = -0.0028258925',
    (abs(
       (0.04 + 0.31 * 0.30)                                        -- K
       * greatest(0.5 + 0.5 * (1 - 0.30), 0.65)                    -- W
       * ((0.85 * 1 + 0.15 * public._v3f5_margin(12, 8))           -- S
          - (1.0 / (1.0 + power(10.0, (1.0 - 6.5) / 1.0))))        -- E
     - (-0.002825892506)) < 1e-9)

  union all select 26, 'G4 really is negative (the winner does lose rating)',
    ((0.04 + 0.31 * 0.30)
     * greatest(0.5 + 0.5 * (1 - 0.30), 0.65)
     * ((0.85 * 1 + 0.15 * public._v3f5_margin(12, 8))
        - (1.0 / (1.0 + power(10.0, (1.0 - 6.5) / 1.0)))) < 0)

  -- G6 — established even teams (3.5 / sigma 0.50 / 30 matches) winning
  -- '6-4,3-6,10-7', i.e. 10 games each. K 0.195, W 0.75, S 0.925.
  union all select 27, 'G6 established, tie-break decider: delta = +0.06215625',
    (abs(
       (0.04 + 0.31 * 0.50)
       * greatest(0.5 + 0.5 * (1 - 0.50), 0.65)
       * ((0.85 * 1 + 0.15 * public._v3f5_margin(10, 10))
          - (1.0 / (1.0 + power(10.0, (3.5 - 3.5) / 1.0))))
     - 0.062156250) < 1e-9)

  -- Placement K ladder: 1.15, 1.1155, 0.84681, 0.8214057, 0.619704967, then
  -- the CLIFF to 0.2928971706 at match 6 (the plain 0.04 + 0.31*sigma).
  union all select 28, 'K at match 5 is 0.6197049670 (validation stage)',
    (abs(0.70 * greatest(0.35, least(1.0, 0.8410281695 / 0.95)) - 0.619704967) < 1e-9)

  union all select 29, 'K at match 6 drops to 0.2928971706 — the cliff is real',
    (abs(0.04 + 0.31 * 0.8157973244 - 0.292897170564) < 1e-9)

  -- Sigma ladder: 0.95 -> 0.8157973244 at the reveal -> 0.7374161675 (m10)
  -- -> 0.5724780137 (m20). Bands 0.970 / 0.980 / 0.975 / 0.970.
  union all select 30, 'sigma after 5 matches is 0.8157973244 (reveal is low-confidence)',
    (abs(round(0.95 * power(0.970, 5), 10) - 0.8157973244) < 1e-9)

  union all select 31, 'sigma after 20 matches is 0.5724780137',
    (abs(round(0.95 * power(0.970,5) * power(0.980,5) * power(0.975,10), 10)
         - 0.5724780137) < 1e-9)

  union all select 32, 'the 0.58 provisional gate brackets matches 19 and 20',
    ((0.95 * power(0.970,5) * power(0.980,5) * power(0.975,9))  > 0.58
     and (0.95 * power(0.970,5) * power(0.980,5) * power(0.975,10)) < 0.58)
)
select case when ok then 'PASS' else '*** FAIL ***' end as result,
       label
  from checks
 order by ok, sort;
